version: "3.9"

services:
  db:
    image: postgres:13.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5433:5432"